### PR TITLE
tr-18632 prometheus scrape velero metrics only to bring down memory usage

### PR DESCRIPTION
**Pull request by wjunkit**

### CODE REVIEW

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **wjunkit**
You can assign the PR to them by writing `/assign @wjunkit` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fobservability).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/trainingrocket/observability/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/observability/pull/432#issuecomment-674621668" title="Approved">sanjevsunder</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fobservability).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/observability/blob/master/OWNERS)~~ [sanjevsunder]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Review by yrcjaya — APPROVED** [review]

**Comment by aquila-droid** [comment]
LGTM label has been added.  <details>Git tree hash: 96fc398366e6c09d42e241094eb3dc8f9daaa23c</details>

**Comment by aquila-droid** [comment]
[APPROVALNOTIFIER] This PR is **APPROVED**

This pull-request has been approved by: *<a href="https://github.com/trainingrocket/observability/pull/432#issuecomment-674621668" title="Approved">sanjevsunder</a>*, *<a href="https://github.com/trainingrocket/observability/pull/432#pullrequestreview-470211007" title="Approved">yrcjaya</a>*

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=trainingrocket%2Fobservability).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details >
Needs approval from an approver in each of these files:

- ~~[OWNERS](https://github.com/trainingrocket/observability/blob/master/OWNERS)~~ [sanjevsunder]

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Pull request merged**
